### PR TITLE
matches suggest with or without quotes

### PR DESCRIPTION
**Pull request by tsop14**
Fixes: #4

### CODE REVIEW

**Comment by chriswilk** [comment]
@alastairjardine have you seen anyone do this?

**Comment by alastairjardine** [comment]
@chriswilk alas, no. it might be a bad idea. thoughts?

**Comment by tsop14** [comment]
**WILL MATCH**
suggest
SUGGEST
"suggest"
'suggest'

**WONT MATCH**
'Suggest' something with cheese
Can you suggest a dessert

**Comment by alastairjardine** [comment]
@tsop14 I don't think I was right on this one – nobody tried to use quotes on testing, so I suggest we drop. Sorry...

**Comment by tsop14** [comment]
no problem!

**Pull request closed without merging**
