### PR TITLE
Support AMI updates via Riff Raff.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
@cb372 Another example of where we probably want a specific image built.

**Comment by cb372** [comment]
This will not work as is, because in UserData it installs Node using a machine-images feature:

```
/opt/features/nodejs/install.sh
```

If you switch the Amigo image to [`ubuntu-wily-node-6`](https://amigo.gutools.co.uk/recipes/ubuntu-wily-node-6) and remove the above line, everything should work. The machine will already have Node installed on it.

**Comment by cb372** [comment]
👍  but my "everything should work" above is not legally binding! You'll have to try it and see if it deploys ok.

**Comment by LATaylor-guardian** [comment]
@cb372 Works on the latest version of your node-6 image. Merging.

**Pull request merged**
